//! Mines blocks on a local regtest chain, end to end.
//!
//! ```text
//! cargo run --release -p regtest-miner -- [block count]
//! ```
//!
//! Regtest difficulty is trivial — the target covers roughly half the hash
//! space — so a block is found in a handful of attempts. That is the point:
//! it makes the mine-and-submit path testable in milliseconds instead of
//! geological time, so the parts that are actually hard to get right (the
//! coinbase, the commitment, the merkle root, the serialisation) can be
//! debugged against a real Bitcoin Core node.
//!
//! Every consensus rule that applies on mainnet applies here too. A block that
//! this accepts is wrong in no way that regtest is lenient about.

mod round;

use bitcoind_rpc::{Network, RpcClient};
use btc_primitives::hex;
use std::path::PathBuf;

/// The wallet used to generate a throwaway payout address on regtest.
const WALLET_NAME: &str = "solo-miner-regtest";

fn main() {
    if let Err(error) = run() {
        eprintln!("error: {error}");

        // Print the whole cause chain: the root is usually the useful part,
        // and Display on the outermost error only shows the top.
        let mut source = error.source();
        while let Some(cause) = source {
            eprintln!("  caused by: {cause}");
            source = cause.source();
        }

        std::process::exit(1);
    }
}

fn run() -> Result<(), Box<dyn std::error::Error>> {
    let blocks_to_mine: u32 = std::env::args()
        .nth(1)
        .map_or(Ok(1), |argument| argument.parse())?;

    let datadir = datadir();
    let client = RpcClient::from_datadir(&datadir, Network::Regtest)?;

    // --- Refuse to mine on a node that is not where we think it is ----------
    let info = client.get_blockchain_info()?;
    if info.chain != Network::Regtest.as_str() {
        return Err(format!(
            "expected a regtest node, but {} is running {}",
            datadir.display(),
            info.chain
        )
        .into());
    }

    println!("node   : regtest at height {}", info.blocks);

    // --- Payout address ------------------------------------------------------
    //
    // Generated by the node's wallet, because on regtest the coins are
    // meaningless. On testnet4 and mainnet this comes from the user instead.
    client.ensure_wallet(WALLET_NAME)?;
    let address = client.get_new_address(WALLET_NAME)?;

    let address_info = client.validate_address(&address)?;
    if !address_info.is_valid {
        return Err(format!("the node produced an address it considers invalid: {address}").into());
    }
    let payout_script = hex::decode(
        address_info
            .script_pubkey
            .as_deref()
            .ok_or("validateaddress returned no scriptPubKey")?,
    )?;

    println!("payout : {address}");
    println!("script : {}\n", hex::encode(&payout_script));

    // --- Mine ----------------------------------------------------------------
    for round_number in 1..=blocks_to_mine {
        let template = client.get_block_template()?;

        // The extranonce must differ per attempt so that a repeated template
        // does not produce a byte-identical block.
        let extranonce = u64::from(round_number);

        match round::mine(&client, &template, &payout_script, extranonce)? {
            round::Outcome::Accepted { hash, height, nonce, hashes } => {
                println!("block {height} accepted");
                println!("  hash   : {hash}");
                println!("  nonce  : {nonce} (found after {hashes} hashes)");
            }
            round::Outcome::Rejected { reason } => {
                return Err(format!("bitcoind rejected the block: {reason}").into());
            }
            round::Outcome::Exhausted { best, best_zero_bits } => {
                return Err(format!(
                    "exhausted the nonce space without a solution \
                     (best was {best}, {best_zero_bits} leading zero bits)"
                )
                .into());
            }
        }
    }

    let info = client.get_blockchain_info()?;
    println!("\nchain is now at height {}", info.blocks);
    println!("tip: {}", info.best_block_hash);

    Ok(())
}

/// Where the node keeps its data. Matches `scripts/node.sh`.
fn datadir() -> PathBuf {
    std::env::var("SOLO_DATADIR").map_or_else(
        |_| {
            PathBuf::from(std::env::var("HOME").expect("HOME is set")).join(".bitcoin-solo")
        },
        PathBuf::from,
    )
}
